default_lang: 'en'
languages: ['en', 'es']

keep_files:
- assets
rsync_copy:
- _assets
exclude:
- sitemap.json
- media.json
- old_media.json
- models.json

page_gen:
  - data: 'amenities'
    template: 'amenity'
    dir: 'amenities'

exclude:
  - 'sitemap.json'
  - 'assets'